### ISSUE TITLE
给楼主点赞，前后端大佬

### ISSUE THREAD

**Issue by WarriorFromLongAgo** [RainbowRW2/rainbow#5]
可惜楼主是 minio 写的，我是准备 netty 写一套。

准备借鉴（抄袭）一下楼主的页面设计，不知道是否可以。
（保证非商业，个人项目）

**Comment by WarriorFromLongAgo** [comment]
楼主随时可以关闭这个issues

**Comment by imczdev** [comment]
> 可惜楼主是 minio 写的，我是准备 netty 写一套。
> 
> 准备借鉴（抄袭）一下楼主的页面设计，不知道是否可以。
> （保证非商业，个人项目）

[rainbow](https://github.com/ch3n90/rainbow) 本身就是用netty和websocket 写的服务。
[minio](https://min.io/) 只是一个对象存储而已。我不知道你是否是想表达mina而手误打成minio

**Comment by imczdev** [comment]
> 楼主随时可以关闭这个issues

本身就是一个开源的项目 apache license 2.0 你可以个人使用也可以商业使用
